In [4]:
import folium
import numpy as np
import pandas as pd
import json

data = json.load(open('../processed_data/distance_duration_matrix.json'))
N_STATIONS = 9

distance_dict = data['distances']
duration_dict = data['durations']

coords_dict = data['destinations']
name_map = {}

coords_matrix = np.empty((N_STATIONS+1, 2))
for key,value in coords_dict.items():
    coords_matrix[int(key), :] = value['location'][::-1]  # reverse to lat,long
    name_map[int(key)] = value['name']

distance_matrix = np.empty((N_STATIONS+1, N_STATIONS+1))
duration_matrix = np.empty((N_STATIONS+1, N_STATIONS+1))

for r in range(N_STATIONS+1):
    distance_matrix[r, :] = distance_dict[str(r)]
    duration_matrix[r, :] = duration_dict[str(r)]

# station_name_to_row = {station_name: idx for idx, station_name in enumerate(stations['station_name'])}

distance_matrix /= 1000  # convert to kilometers
distance_matrix = distance_matrix.astype(np.float32)
print("Distance matrix (in kilometers):")
print(distance_matrix[-5:,-5:])

duration_matrix /= 60  # convert to seconds
duration_matrix = duration_matrix.astype(np.float32)
print("Duration matrix (in seconds):")
print(duration_matrix[-5:,-5:])

# my_map3 = folium.Map(location = [avg_location[0], avg_location[1]], zoom_start = 12)


Distance matrix (in kilometers):
[[ 0.     16.8571 14.304   4.9001 12.253 ]
 [15.682   0.      3.4166 11.0404  8.1104]
 [15.5268  3.3297  0.     10.8852  4.3621]
 [ 4.1128 11.6898  9.1366  0.      7.3957]
 [14.5784  8.0751  4.4142  7.5515  0.    ]]
Duration matrix (in seconds):
[[ 0.        20.523333  19.61       8.35      20.271667 ]
 [21.605      0.         6.4133334 16.44      13.213333 ]
 [20.153334   5.3416667  0.        14.988334   7.1016665]
 [ 8.341666  15.29      14.376667   0.        15.261666 ]
 [21.226667  12.405      7.2733335 15.608334   0.       ]]


In [10]:
my_map3 = folium.Map(location = [np.mean(coords_matrix[:,0]), np.mean(coords_matrix[:,1])], zoom_start = 12)

for i in name_map.keys():
    folium.Marker(location = [coords_matrix[i,0], coords_matrix[i,1]], 
                  popup = i,
                  icon=folium.Icon(color='blue', icon='info-sign')
                 ).add_to(my_map3)
my_map3



In [15]:
distance_matrix[8, 1]
# distance_matrix[8, 1]

np.float32(5.3088)